export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const LOAD_STOPS_SUCCESS = 'LOAD_LIST_SUCCESS';
export const PREDICATION_SUCCESS = 'LOAD_LIST_SUCCESS';

export const UPDATE_CAT_SUCCESS = 'UPDATE_CAT_SUCCESS';
export const CREATE_CAT_SUCCESS = 'CREATE_CAT_SUCCESS';
export const DELETE_CAT_SUCCESS = 'DELETE_CAT_SUCCESS';