export const LOAD_ROUTES_SUCCESS = 'LOAD_LIST_SUCCESS';
export const CHANGE_ROUTELIST = 'CHANGE_ROUTELIST';
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';  
export const SELECT_STOP = 'SELECT_STOP';
