export const LOAD_ROUTES_SUCCESS = 'LOAD_ROUTES_SUCCESS';
export const LOAD_STOPS_SUCCESS = 'LOAD_STOPS_SUCCESS';
export const LOAD_DIRECTION_SUCCESS = 'LOAD_DIRECTION_SUCCESS';
export const LOAD_PREDICATION_SUCCESS = 'LOAD_PREDICATION_SUCCESS';

export const CHANGE_ROUTELIST = 'CHANGE_ROUTELIST';
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';  
export const CHANGE_STOP = 'CHANGE_STOP';

